[project]
name = "mcp-demo"
version = "0.1.0"
description = "Simple MCP Server and Client demo with AWS Bedrock"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mcp>=1.0.0",
    "boto3>=1.34.0"
]
